### ISSUE TITLE
Feedback on sorting algorithms

### ISSUE THREAD

**Issue by Anisha7** [dmcg89/CS-2.1-Trees-Sorting#1]
What was great:
- Good job on implementing your is_sorting function efficiently! 
- Good job on successfully implementing your sorting algorithms!

Here's some feedback to improve:
- Your split_sort_merge fails unit tests! Work through the failed tests to debug your code! :)
- Try adding a couple more test cases! It may seem intimidating at first, but you've made it past the hard part. Implementation is way tougher than calling these functions and comparing inputs. In the work environment, writing tests will be required. Its a good habit to build :) 
- Annotate time and space complexities for all of your functions!

**Comment by dmcg89** [comment]
More tests are written, split_sort_merge works and is now done in place.  All annotations are done
